#!/bin/bash
abc="'mp3/$1.abc'"
mid="'mp3/$1.mid'"
wav="'mp3/$1.wav'"
fastwav="'mp3/fast$1.wav'"
mp3="'mp3/$1.mp3'"
title="$2"
artist="\"TheSession\""
genre="\"folk\""

echo "processing $abc to $mid"
eval "abc2midi $abc -o $mid"
eval "timidity $mid -Ow -o $wav"
eval "sox -q $wav $fastwav  tempo 1.33"
eval "sox  $fastwav $mp3"
eval "id3v2 -t  \"$title\" $mp3"
eval "id3v2 -g \"folk\" $mp3"
eval "id3v2  -l \"The Session\"  $mp3"

eval "rm $wav"
eval "rm $fastwav"
eval "rm $mid"
