#!/bin/bash
abc="'mp3/$@.abc'"
mid="'mp3/$@.mid'"
wav="mp3/'$@.wav'"
mp3="mp3/'$@.mp3'"
echo "processing $abc to $mid"
eval "abc2midi $abc -o $mid"
eval "timidity $mid -Ow -o $wav"
eval "sox $wav $mp3 speed 1.33"
eval "rm $wav"
eval "rm $mid"
